### ISSUE TITLE
The Roblox wiki sub domain is not implemented

### ISSUE THREAD

**Issue by Puffinlump** [sentanos/rprxy#2] opened 2017-11-25 18:00 UTC
I'm currently trying to access http://wiki.roblox.com/index.php/API:Class_reference/Dump/raw?action=raw so I can parse it. Your proxy does not support the wiki sub domain... I'd love it if you could add this!

**Comment by sentanos** [comment] 2017-11-26 01:28
I looked into this because actually the ROBLOX wiki subdomain has been added. The issue is happening because although wiki.roblox.com does not allow https, all proxy requests are made https anyways. The wiki returns a 502 error when you attempt to use https which is then proxied to the user but cloudflare adds a custom error page.

This will be fixed in a patch very soon.

**Closed** 2017-11-26 01:29 UTC
